
declare module "@editorjs/header"
declare module "@editorjs/"
declare module "@editorjs/link";
declare module "@editorjs/raw";
declare module "@editorjs/checklist";
declare module "@editorjs/simple-image";
declare module "@editorjs/embed";
declare module "@editorjs/quote";
declare module "@editorjs/paragraph";
declare module "@editorjs/table";
declare module "@editorjs/nested-list";
declare module "@editorjs/text-variant-tune";
declare module "@editorjs/underline";
declare module "@editorjs/inline-code";
declare module "@editorjs/code";
declare module "@editorjs/warning";
declare module "@editorjs/marker";
declare module "@editorjs/attaches";
declare module "@editorjs/delimiter";